:PROPERTIES:
:header-args: :results silent
:END:
#+title:
#+author: Aaron Kunde
#+email: aaron.kunde@web.de
Description and examples to set up [[https://www.gnupg.org/][The GNU Privacy Gurad]] key management-

* Overview
The basic setup is based on https://wiki.debian.org/Subkeys. This will create one primary signing key pair, which should never be stored on the machine. Instead, subkeys are used for the daily work like encrypting or signing messages. The primary key pair is stored on a portable media, like an USB disk and only mounted and used, when needed. The backups of the current key setup together with their primary keys are stored on the media as well. The file structure of the media should look like something like:
#+begin_example
  +-README.org
  +-bak/
    |-gnupg.0.tar
    |-gnupg.1.tar
  ...
    +-gnupg.N.tar
#+end_example

The file =README.org= is this file. The files =gnupg.<x>.tar= are backups, with =gnupg.0.tar= the first and =gnupg.N.tar= the most current.

* Mount USB
To work with the primary signing keys, the media, on which they are stored, needs to be mounted.

** Mount USB device on Linux
There are several ways to mount USB media on Linux. One is to use =udisksctl= which is provided by [[https://packages.debian.org/de/trixie/udisks2][udisks2]]:
#+begin_example shell
  udisksctl mount -b /dev/<device>
#+end_example

After that the device is accessible at =/media/$USER/=.

** Mount USB device within WSL
If the USB device is attached, it can be mounted with the =mount= command. The following example mounts a USB device, which is assigned to the device /D:/ to =/media/=:
#+begin_example shell :dir /sudo::
  mount -t drvfs -o uid=$(id -u $USER),gid=$(id -g $USER) d: /media/
#+end_example

* Prepare
To create the setup or manage keys, some preparation has to be done.

** Stop gpg-agent
Stop eventually running gpg-agents:
#+begin_src shell
  gpgconf --kill gpg-agent
#+end_src

** Create temporary backup
Make a temporary backup of the current ~$HOME/.gnupg~ if something goes wrong:
#+begin_src shell
  mv ~/.gnupg ~/gnupg.bak
#+end_src

** Create a temporary GnuPG home directory
Create a temporary GnuPG home directory in the current working directory.

1. Set GnuPG homedir to the temporary directory. The variable ~$GNUPGHOME~ is set to the current working directory. It needs to be exported, otherwise it is not respected in the following commands:
   #+begin_src shell :session manage-pgphome
     export GNUPGHOME=$PWD/gnupg-wd
   #+end_src

2. Create the directory:
   #+begin_src shell :session manage-pgphome
     mkdir -p $GNUPGHOME
   #+end_src

3. Change permissions for directory:
   #+begin_src shell :session manage-pgphome
     chmod 0700 $GNUPGHOME
   #+end_src

* Create an initial setup
The initial setup has to be done once.

** Create a new primary key pair
Creating a new primary keypair should be done interactively, at least for setting a password. The following procedure is based on [[https://keyring.debian.org/creating-key.html][Creating a new GPG key]], but  uses the full key generation to set algorithms and expiration date interactively. The fingerprint of the key is stored in the variable ~$gnupg_fpr~ for later use, which only works, if an expiration date is set:
#+begin_example shell
  gnupg_fpr=$(gpg --full-gen-key | grep -A1 -e '^pub' | tr -d '\n' | tr -s ' ' | cut -d ' ' -f 7)
#+end_example

*Note*: It is assumed, that the keys are be valid for one year.

** Add a subkey for signing
Like described at https://wiki.debian.org/Subkeys, a subkey for signing with the default algorithm is added. This key should be valid for one year as well:
#+begin_example shell
  gpg --quick-add-key $gnupg_fpr default sign 1y
#+end_example

** Verify
To verify the basic setup. list the public keys:
#+begin_src shell :session manage-pgphome :results verbatim :var LANG="en"
  gpg -K
#+end_src

This should result to something like:
: ------------------------------------------------
: sec   ed25519 2025-11-16 [SC] [expires: 2026-11-16]
:       1AD50F30FFFB994233881FA61B41057B207BCE90
: uid           [ultimate] John Doe (Dummy ID) <j.d@mai.le>
: ssb   cv25519 2025-11-16 [E] [expires: 2026-11-16]
: ssb   ed25519 2025-11-16 [S] [expires: 2026-11-16]

* Manage keys
After the initial setup, key management can be done in multiple ways. Since always a password should be set, it is not possible to do it fully automatically.

* Create backup
To create a backup of the keys. The backups are stored in tar archives starting with =gnupg.0.tar=. The next backup has then :

1. Stop the gpg-agent
   #+begin_src shell :session manage-pgphome
     gpgconf --kill gpg-agent
   #+end_src

2. Remove old lock files
   #+begin_src shell :session manage-pgphome
     rm -f $GNUPGHOME/.#lk0x*
   #+end_src

3. Create a new tar archive of the temporary GnuPG home directory with an incremented number
   #+begin_src shell
     tar cf bak/gnupg.$(find bak -maxdepth 1 -name '*.tar' | wc -l).tar gnupg-wd
   #+end_src

* Cleanup
After finishing, some cleanup needs to be done.

1. Stop the gpg-agents for the temporary GnuPG home directory:
   #+begin_src shell :session manage-pgphome
     gpgconf --kill gpg-agent
   #+end_src

2. Delete the temporary GnuPG home directory:
   #+begin_src shell :session manage-pgphome
     rm -rf $GNUPGHOME
   #+end_src

3. Unset =$GNUPGHOME=:
   #+begin_src shell :session manage-pgphome
     unset GNUPGHOME
   #+end_src

* Install from Backup
The managed keys can then be installed from the current backup to default GnuPG homedir =$HOME/.gnupg=, without private sign key.

1. Create a temporary directory to extract the files to:
   #+begin_src shell :session manage-pgphome
     mkdir -p $PWD/gnupg-tmp
   #+end_src

2. Determine the fingerprints of the primary private keys. Extract all files from the current archive, without the primary private keys:
   #+begin_src shell :session manage-pgphome
     gnupg_exclusions=$(gpg -K --with-keygrip \
     	| grep -e '^sec ' -A 2 \
     	| sed -nE 's/ *Keygrip = ([0-9A-F]+)/--exclude=private-keys-v1.d\/\1.key/p')
     tar -C $PWD/gnupg-tmp $gnupg_exclusions \
         -xf bak/gnupg.$(($(find bak -maxdepth 1 -name '*.tar' | wc -l) - 1)).tar
     unset gnupg_exclusions
   #+end_src

3. Make the extracted files the new target GnuPG homedir =$HOME/.gnupg=:
   #+begin_src shell :session manage-pgphome
     mv $PWD/gnupg-tmp/gnupg-wd ~/.gnupg
   #+end_src

4. Remove temporary directory:
   #+begin_src shell :session manage-pgphome
     rmdir $PWD/gnupg-tmp
   #+end_src

** Verify
To verify, check the public keys for not having a private key. Their entries should start with =sec#=.

The execution of:
#+begin_src shell :results replace verbatim :var LANG="en"
  gpg --homedir ~/.gnupg -K | grep -e 'sec#'
#+end_src

should result to something like:
: sec#  ed25519 2025-11-16 [SC] [expires: 2026-11-16]

The execution of the following command should not produce any output:
#+begin_src shell :var LANG="en"
  gpg --homedir ~/.gnupg -K | grep -e 'sec '
#+end_src

* Sync in WSL
Within WSL the newly created gpg keys might be shared to the usual user environment within Windows:
#+begin_src shell
  rm -rf /mnt/c/Users/$USER/.gnupg
  cp -r ~/.gnupg /mnt/c/Users/$USER/
#+end_src

* Remove temporary backup
Temporary backup might be removed:
#+begin_src shell
  rm -rf ~/gnupg.bak
#+end_src

* Unmount USB
After that the device is accessible at =/media/$USER/=.
Depending on the method for mounting, the USB device needs to be unmounted.

** Unmount USB device on Linux
If the device was mounted with =udisksctl=, it can be unmounted with:
#+begin_example shell
  udisksctl unmount -b /dev/<device>
#+end_example

** Unmount USB device within WSL
In WSL the device can be unmounted with:
#+begin_src shell :dir /sudo:: :results silent
  umount /media
#+end_src
