:PROPERTIES:
:header-args: :results silent
:END:
#+title:
#+author: Aaron Kunde
#+email: aaron.kunde@web.de
Description and examples to set up [[https://www.gnupg.org/][The GNU Privacy Gurad]] key management-

* Overview
The basic setup is based on https://wiki.debian.org/Subkeys, which will create one primary signing key pair, which should never be stored on the machine. Instead, subkeys are used for the daily work like encrypting or signing messages. The primary key pair is stored on a portable media, like an USB disk and only mounted and used, when needed. The backups of the current key setup together with their primary keys are stored on the media as well. The file structure of the media should look like something like:
#+begin_example
  +-README.org
  +-gnupg.0.tar
  +-gnupg.1.tar
  ...
  +-gnupg.N.tar
#+end_example

With =README.org= is this file and =gnupg.<x>.tar= are backups, with =gnupg.0.tar= the first and =gnupg.N.tar= the most current.

* Mount USB
To work with the primary signing keys, the media, on which they are stored, needs to be mounted.

** Mount USB device on Linux
There are several ways to mount USB media on Linux. One is to use =udisksctl= which is provided by [[https://packages.debian.org/de/trixie/udisks2][udisks2]]:
#+begin_example shell
  udisksctl mount -b /dev/<device>
#+end_example

After that the device is accessible at =/media/$USER/=.

** Mount USB device within WSL
If the USB device is attached, it can be mounted with the =mount= command. The following example mounts a USB device, which is assigned to the device /D:/ to =/media/=:
#+begin_example shell :dir /sudo::
  mount -t drvfs -o uid=$(id -u $USER),gid=$(id -g $USER) d: /media/
#+end_example

* Prepare

** Kill gpg-agent
Kill eventually running gpg-agents:
#+begin_src shell
  gpgconf --kill gpg-agent
#+end_src

** Create temporary backup
Make a temporary backup of the current ~$HOME/.gnupg~ if something goes wrong:
#+begin_src shell
  cp -r ~/.gnupg ~/gnupg.bak
#+end_src

** Create a temporary GnuPG home directory
Create a temporary GnuPG home directory in the current working directory.

1. Set GnuPG homedir to the temporary directory. The variable ~$GNUPGHOME~ is set to the current working directory. It needs to be exported, otherwise it is not respected in the following commands:
   #+begin_src shell :session manage-pgphome
     export GNUPGHOME=$PWD/gnupg-wd
   #+end_src

2. Create the directory:
   #+begin_src shell :session manage-pgphome
     mkdir -p $GNUPGHOME
   #+end_src

3. Change permissions for directory:
   #+begin_src shell :session manage-pgphome
     chmod 0700 $GNUPGHOME
   #+end_src
